pipelines:
  - name: onboard_talet_pipelines_dist
    steps:
      - name: rb_create
        type: CreateReleaseBundle
        configuration:
          #inherits from bash
          releaseBundleName: pipeline-release-bundle
          releaseBundleVersion: 1.0.${run_number}
          storeAtSourceArtifactory: "true"
          dryRun: false   # default true
          sign: false   # default false

          inputResources:
            - name: rb_aql        # one Aql
          outputResources:
            - name: rb_pipeline

        execution:
          onStart:
            - echo "Creating release bundle..."
          onSuccess:
            - echo "Success!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
      - name: rb_sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: rb_pipeline  # required
              trigger: false
          outputResources:
            - name: rb_pipeline_signed  # required
          inputSteps:
            - name: rb_create

        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"